version: 2

updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows/sync/
    schedule:
      interval: weekly
  - dependency-names: actions/Fork-Sync-With-Upstream-action
  # it only does upstream sync the actual sync action
  # upstream sync's checkout must be done manually
