version: 2

updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows/sync/
    schedule:
      interval: weekly
    allow:
      - dependency-name: actions/Fork-Sync-With-Upstream-action
        # only does upstream sync's actual sync action
        # upstream sync checkout action must be updated manually
