name: feature request
description: this form is for requesting new features only in the frontend so like with ui or buttons
labels: ["Triage", "Feature"]
body:
  - type: textarea
    id: desc
    attributes:
      label: feature description
      description: what new feature you would like to see
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: reasoning
      description: why is it needed
    validations:
      required: true
