name: Deploy to Pages

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "index.html"
      - "info.html"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/pages.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v6
        with:
          version: 12.4.1

      - uses: actions/setup-node@v7
        with:
          node-version: 26.9.0
      - run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://".insteadOf git://
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build --base=slowroute
      - run: cd dist; echo > .nojekyll; cd ..
      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
